language: "en"

policies:
  - name: RulePolicy

rules:
- rule: Say `hello` whenever the user sends a message with intent `greet`
  conversation_start: true
  steps:
  - intent: greet
  - action: utter_greet